//GLOBAL VARIABLES SECTION

//CONSTANTS

MAX_NPCS <- 20;
NPC_FOLLOWDISTANCE <- 50;
ZOMBIE_WORLD <- 3;
ZOMBIE_FROZEN <- 0;
ZOMBIE_INSTAKILL <- 0;
ZOMBIE_DOUBLE <- 0;
ZOMBIE_IMMUNITY <- 0;
ZOMBIE_SPEED <- 0.2;
ZOMBIE_MUTED <- false;

//** INSERT ACTUAL NPCS USING BOTS**

